### ISSUE TITLE
Warning: socket_set_option(): unable to set socket option [92]: Protocol not available

### ISSUE THREAD

**Issue by mabu233** [easy-swoole/rpc#1]
[https://github.com/easy-swoole/rpc/blob/master/src/Rpc.php#L293](https://github.com/easy-swoole/rpc/blob/master/src/Rpc.php#L293)
改为 socket_set_option($sock, SOL_SOCKET, SO_BROADCAST, true); 解决

**Comment by kiss291323003** [comment]
感谢
