### ISSUE TITLE
关于使用CLI独立测试的demo代码时的问题

### ISSUE THREAD

**Issue by kjkq763** [easy-swoole/rpc#14]
在使用文档上的测试代码时,如下

> <?php
> /**
>  * Created by PhpStorm.
>  * User: xcg
>  * Date: 2019/5/30
>  * Time: 9:19
>  */
> require_once 'vendor/autoload.php';
> 
> use EasySwoole\Rpc\Config;
> use EasySwoole\Rpc\Rpc;
> use EasySwoole\Rpc\NodeManager\RedisManager;
> use EasySwoole\Rpc\Response;
> 
> //cli模拟，跨进程，重新new rpc对象
> $config = new Config();
> $nodeManager = new RedisManager('127.0.0.1');
> $config->setNodeManager($nodeManager);
> $rpc = new Rpc($config);
> 
> go(function () use ($rpc) {
>     $client = $rpc->client();
>     $client->addCall('UserService', 'register', ['arg1', 'arg2'])
>         ->setOnFail(function (Response $response) {
>             print_r($response->toArray());
>         })
>         ->setOnSuccess(function (Response $response) {
>             print_r($response->toArray());
>         });
> 
>     $client->exec();
> });

一直返回

> Array
> (
>     [result] =>
>     [status] => 1001
>     [nodeId] =>
>     [msg] =>
> )

最后在redismanager.php发现hgetall这里获取所有所有的域和值,在foreach循环里面,就出现报错,导致问题所在,所以我加上一个判断后,就正常了.如下
> function getServiceNodes(string $serviceName, ?string $version = null): array
>     {
>         /** @var \Redis $redis */
>         $redis = PoolManager::getInstance()->getPool('__rpcRedis')->getObj(15);
>         try {
>             $nodes = $redis->hGetAll($this->redisKey . md5($serviceName));
>             $nodes = $nodes ?: [];
>             $ret = [];
>             foreach ($nodes as $nodeId => $node) {
```
>                 if ($node instanceof ServiceNode) {
>                     /**
>                      * @var  $nodeId
>                      * @var  ServiceNode $node
>                      */
>                     if (time() - $node->getLastHeartBeat() > 30) {
>                         $this->deleteServiceNode($node);
>                     }
>                     if ($version && $version != $node->getServiceVersion()) {
>                         continue;
>                     }
>                     $ret[$nodeId] = $node;
>                 }
>             }
```
>             return $ret;
>         } catch (\Throwable $throwable) {
>             //如果该redis断线则销毁
>             PoolManager::getInstance()->getPool('__rpcRedis')->unsetObj($redis);
>         } finally {
>             //这边需要测试一个对象被unset后是否还能被回收
>             PoolManager::getInstance()->getPool('__rpcRedis')->recycleObj($redis);
>         }
>         return [];
>     }
(编辑不好,请见谅)

**Comment by zhoper** [comment]
是的，hgetall获取到的数据，和预期不一样
![image](https://user-images.githubusercontent.com/40931/59793318-d8554880-9308-11e9-86e8-dfa005042e6c.png)

**Comment by xiaocaigua** [comment]
请把swoole 升级到4.4.x
具体可以看这边文章
https://wiki.swoole.com/wiki/page/1091.html
