### ISSUE TITLE
服务端出错了

### ISSUE THREAD

**Issue by jingqianwei** [easy-swoole/rpc#17]
PHP Fatal error:  Uncaught TypeError: Return value of EasySwoole\Rpc\BroadcastCommand::getServiceNode() must be an instance of EasySwoole\Rpc\ServiceNode or null, array returned in /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/BroadcastCommand.php:38
Stack trace:
#0 /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/TickProcess.php(68): EasySwoole\Rpc\BroadcastCommand->getServiceNode()
#1 {main}
  thrown in /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/BroadcastCommand.php on line 38

Fatal error: Uncaught TypeError: Return value of EasySwoole\Rpc\BroadcastCommand::getServiceNode() must be an instance of EasySwoole\Rpc\ServiceNode or null, array returned in /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/BroadcastCommand.php:38
Stack trace:
#0 /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/TickProcess.php(68): EasySwoole\Rpc\BroadcastCommand->getServiceNode()
#1 {main}
  thrown in /mnt/c/phpStudy/WWW/swooleRpc/vendor/easyswoole/rpc/src/BroadcastCommand.php on line 38

**Comment by kiss291323003** [comment]
看最新文档，去更新
