### ISSUE TITLE
composer安装RPC插件版本冲突

### ISSUE THREAD

**Issue by promisingccy** [easy-swoole/rpc#18]
swoole version                4.4.7
php version                   7.3.6
easy swoole                   3.3.1

[root@localhost easyswoole-rpc]# composer require easyswoole/rpc=4.x
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install easyswoole/rpc 4.0.5
    - Conclusion: don't install easyswoole/rpc 4.0.4
    - Conclusion: don't install easyswoole/rpc 4.0.3
    - Conclusion: don't install easyswoole/rpc 4.0.2
    - Conclusion: remove easyswoole/component 2.0.3
    - Installation request for easyswoole/rpc 4.x -> satisfiable by easyswoole/rpc[4.0.1, 4.0.2, 4.0.3, 4.0.4, 4.0.5].
    - Conclusion: don't install easyswoole/component 2.0.3
    - easyswoole/rpc 4.0.1 requires easyswoole/component ^1.7 -> satisfiable by easyswoole/component[1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.8.0, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.9.0, 1.9.1, 1.9.2].
    - Can only install one of: easyswoole/component[1.7.1, 2.0.3].
    - Can only install one of: easyswoole/component[1.7.2, 2.0.3].
    - Can only install one of: easyswoole/component[1.7.3, 2.0.3].
    - Can only install one of: easyswoole/component[1.7.4, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.0, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.1, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.2, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.3, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.4, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.5, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.6, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.7, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.8, 2.0.3].
    - Can only install one of: easyswoole/component[1.8.9, 2.0.3].
    - Can only install one of: easyswoole/component[1.9.0, 2.0.3].
    - Can only install one of: easyswoole/component[1.9.1, 2.0.3].
    - Can only install one of: easyswoole/component[1.9.2, 2.0.3].
    - Installation request for easyswoole/component (locked at 2.0.3) -> satisfiable by easyswoole/component[2.0.3].

Installation failed, reverting ./composer.json to its original content.
[root@localhost easyswoole-rpc]#

**Comment by kiss291323003** [comment]
移除对component的依赖
重新引入
