### ISSUE TITLE
Swoole\Coroutine\Socket::recvfrom: API must be called in the coroutine

### ISSUE THREAD

**Issue by dlovyi** [easy-swoole/rpc#9]
#0  Swoole\Coroutine\Socket->recvfrom() called at [/var/www/html/emp/api/vendor/easyswoole/rpc/src/AutoFind/Process.php:47]
#1  EasySwoole\Rpc\AutoFind\Process->run() called at [/var/www/html/emp/api/vendor/easyswoole/component/src/Process/AbstractProcess.php:119]

**Comment by kiss291323003** [comment]
composer up下即可
